// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX_6te6OGd-T2wu4i0awTEvyZWC2d2NaU',
    appId: '1:1029124182197:web:2dc163ccaa6b66bb076efc',
    messagingSenderId: '1029124182197',
    projectId: 'parcial4-46f54',
    authDomain: 'parcial4-46f54.firebaseapp.com',
    storageBucket: 'parcial4-46f54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEHY99HSxDvT69F7fs5c91IRBAbGzBxc',
    appId: '1:1029124182197:android:00123a422ea5255b076efc',
    messagingSenderId: '1029124182197',
    projectId: 'parcial4-46f54',
    storageBucket: 'parcial4-46f54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTPl950vxCvQpYOKRj8MRH6mfaQFzB0ig',
    appId: '1:1029124182197:ios:065bdcbf86987d9f076efc',
    messagingSenderId: '1029124182197',
    projectId: 'parcial4-46f54',
    storageBucket: 'parcial4-46f54.appspot.com',
    iosClientId: '1029124182197-mbk57ec6jt8apv7c2cgjglv2hnlj8f4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial42517112018',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTPl950vxCvQpYOKRj8MRH6mfaQFzB0ig',
    appId: '1:1029124182197:ios:065bdcbf86987d9f076efc',
    messagingSenderId: '1029124182197',
    projectId: 'parcial4-46f54',
    storageBucket: 'parcial4-46f54.appspot.com',
    iosClientId: '1029124182197-mbk57ec6jt8apv7c2cgjglv2hnlj8f4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial42517112018',
  );
}
